_wandb:
    value:
        cli_version: 0.24.0
        e:
            zz134n0oum46pr4i08uezc4c656o9l5o:
                args:
                    - --config
                    - train_settings_modified.yaml
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "502392610816"
                        used: "126642585600"
                email: camilo.prada@uni.lu
                executable: /home/ubadmin/.pyenv/versions/torchkrates_implementation/bin/python3.13
                git:
                    commit: d3834b0200b63993a8b1ec7a116a64d7040de070
                    remote: https://github.com/CPradaL/So3krates-torch.git
                host: ubadmin-Dell-Pro-14-Premium-PA14250
                memory:
                    total: "33196122112"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/ubadmin/.pyenv/versions/torchkrates_implementation/bin/torchkrates-train
                python: CPython 3.13.7
                root: /home/ubadmin/Documents/training_control/Torchkrates_implementation/So3krates-torch/examples/training
                startedAt: "2026-01-21T15:11:51.223340Z"
                writerId: zz134n0oum46pr4i08uezc4c656o9l5o
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 41
                - 77
                - 105
            "2":
                - 1
                - 41
                - 77
                - 105
            "3":
                - 13
            "4": 3.13.7
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
